# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.7.3.dev2+g02bcad6.d20220809'
__version_tuple__ = version_tuple = (0, 7, 3, 'dev2', 'g02bcad6.d20220809')
