name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check .
      - run: codespell
      - run: flake8 . --count --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
