name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: |
        python -m pip install --upgrade pip
        pip install wheel

    - run: pip install -e .
    - run: python setup.py sdist bdist_wheel

    - uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{secrets.PYPI_TOKEN}}
